[package]
name = "calculator-mp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "calculator"
path = "./calculator/src/main.rs"

[dependencies]
